// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProcesosService.Infrastructure.Persistence;

#nullable disable

namespace ProcesosService.Migrations
{
    [DbContext(typeof(ProcesoDbContext))]
    [Migration("20260409051710_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProcesosService.Domain.Entities.CompraCabecera", b =>
                {
                    b.Property<int>("IdCompra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCompra"));

                    b.Property<decimal>("Descuento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("FechaCompra")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("IVA")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<string>("IdentificacionComprador")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NombreClienteFactura")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NumeroComprobante")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TipoIdentificacionComprador")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdCompra");

                    b.HasIndex("NumeroComprobante")
                        .IsUnique();

                    b.ToTable("ComprasCabecera", (string)null);
                });

            modelBuilder.Entity("ProcesosService.Domain.Entities.CompraDetalle", b =>
                {
                    b.Property<int>("IdDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetalle"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("CodigoProducto")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("DescripcionProducto")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("nvarchar(220)");

                    b.Property<int>("IdCompra")
                        .HasColumnType("int");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SubtotalLinea")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdDetalle");

                    b.HasIndex("IdCompra");

                    b.HasIndex("IdProducto");

                    b.ToTable("ComprasDetalle", (string)null);
                });

            modelBuilder.Entity("ProcesosService.Domain.Entities.Producto", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProducto"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("CodigoProducto")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("IdProducto");

                    b.HasIndex("CodigoProducto")
                        .IsUnique();

                    b.ToTable("Productos", (string)null);

                    b.HasData(
                        new
                        {
                            IdProducto = 1,
                            Activo = true,
                            CodigoProducto = "MRT-001",
                            Marca = "Truper",
                            Nombre = "Martillo 16oz",
                            Precio = 8.50m,
                            Stock = 50
                        },
                        new
                        {
                            IdProducto = 2,
                            Activo = true,
                            CodigoProducto = "DST-001",
                            Marca = "Stanley",
                            Nombre = "Destornillador Phillips",
                            Precio = 4.25m,
                            Stock = 120
                        },
                        new
                        {
                            IdProducto = 3,
                            Activo = true,
                            CodigoProducto = "TLL-001",
                            Marca = "Bosch",
                            Nombre = "Taladro Inalambrico",
                            Precio = 95.00m,
                            Stock = 20
                        });
                });

            modelBuilder.Entity("ProcesosService.Domain.Entities.CompraDetalle", b =>
                {
                    b.HasOne("ProcesosService.Domain.Entities.CompraCabecera", "CompraCabecera")
                        .WithMany("Detalles")
                        .HasForeignKey("IdCompra")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProcesosService.Domain.Entities.Producto", "Producto")
                        .WithMany("ComprasDetalle")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CompraCabecera");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("ProcesosService.Domain.Entities.CompraCabecera", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("ProcesosService.Domain.Entities.Producto", b =>
                {
                    b.Navigation("ComprasDetalle");
                });
#pragma warning restore 612, 618
        }
    }
}
