// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProcesosService.Infrastructure.Persistence;

#nullable disable

namespace ProcesosService.Migrations
{
    [DbContext(typeof(ProcesoDbContext))]
    partial class ProcesosDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProcesosService.Domain.Entities.CompraCabecera", b =>
                {
                    b.Property<int>("IdCompra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCompra"));

                    b.Property<decimal>("Descuento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("FechaCompra")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("IVA")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<string>("IdentificacionComprador")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NombreClienteFactura")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NumeroComprobante")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TipoIdentificacionComprador")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdCompra");

                    b.HasIndex("NumeroComprobante")
                        .IsUnique();

                    b.ToTable("ComprasCabecera", (string)null);
                });

            modelBuilder.Entity("ProcesosService.Domain.Entities.CompraDetalle", b =>
                {
                    b.Property<int>("IdDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetalle"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("CodigoProducto")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("DescripcionProducto")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("nvarchar(220)");

                    b.Property<int>("IdCompra")
                        .HasColumnType("int");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SubtotalLinea")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdDetalle");

                    b.HasIndex("IdCompra");

                    b.HasIndex("IdProducto");

                    b.ToTable("ComprasDetalle", (string)null);
                });

            modelBuilder.Entity("ProcesosService.Domain.Entities.Producto", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProducto"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("CodigoProducto")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("IdProducto");

                    b.HasIndex("CodigoProducto")
                        .IsUnique();

                    b.ToTable("Productos", (string)null);

                    b.HasData(
                        new
                        {
                            IdProducto = 1,
                            Activo = true,
                            CodigoProducto = "CEM-001",
                            Marca = "Holcim",
                            Nombre = "Cemento Portland",
                            Precio = 8.75m,
                            Stock = 200
                        },
                        new
                        {
                            IdProducto = 2,
                            Activo = true,
                            CodigoProducto = "CLA-001",
                            Marca = "Truper",
                            Nombre = "Clavos 2 pulgadas",
                            Precio = 1.95m,
                            Stock = 1000
                        },
                        new
                        {
                            IdProducto = 3,
                            Activo = true,
                            CodigoProducto = "MRT-001",
                            Marca = "Stanley",
                            Nombre = "Martillo 16oz",
                            Precio = 12.50m,
                            Stock = 75
                        },
                        new
                        {
                            IdProducto = 4,
                            Activo = true,
                            CodigoProducto = "PIN-001",
                            Marca = "Sika",
                            Nombre = "Pintura blanca 1 galon",
                            Precio = 18.90m,
                            Stock = 60
                        },
                        new
                        {
                            IdProducto = 5,
                            Activo = true,
                            CodigoProducto = "BRO-001",
                            Marca = "Truper",
                            Nombre = "Brocha 2 pulgadas",
                            Precio = 2.40m,
                            Stock = 150
                        },
                        new
                        {
                            IdProducto = 6,
                            Activo = true,
                            CodigoProducto = "TAL-001",
                            Marca = "Bosch",
                            Nombre = "Taladro inalambrico",
                            Precio = 95.00m,
                            Stock = 25
                        },
                        new
                        {
                            IdProducto = 7,
                            Activo = true,
                            CodigoProducto = "DST-001",
                            Marca = "Stanley",
                            Nombre = "Destornillador Phillips",
                            Precio = 4.25m,
                            Stock = 120
                        },
                        new
                        {
                            IdProducto = 8,
                            Activo = true,
                            CodigoProducto = "LLA-001",
                            Marca = "Truper",
                            Nombre = "Llave inglesa 10 pulgadas",
                            Precio = 7.80m,
                            Stock = 80
                        },
                        new
                        {
                            IdProducto = 9,
                            Activo = true,
                            CodigoProducto = "TOR-001",
                            Marca = "Fixer",
                            Nombre = "Tornillos galvanizados x100",
                            Precio = 3.60m,
                            Stock = 300
                        },
                        new
                        {
                            IdProducto = 10,
                            Activo = true,
                            CodigoProducto = "PVC-001",
                            Marca = "Amanco",
                            Nombre = "Tuberia PVC 4 metros",
                            Precio = 6.95m,
                            Stock = 90
                        });
                });

            modelBuilder.Entity("ProcesosService.Domain.Entities.CompraDetalle", b =>
                {
                    b.HasOne("ProcesosService.Domain.Entities.CompraCabecera", "CompraCabecera")
                        .WithMany("Detalles")
                        .HasForeignKey("IdCompra")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProcesosService.Domain.Entities.Producto", "Producto")
                        .WithMany("ComprasDetalle")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CompraCabecera");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("ProcesosService.Domain.Entities.CompraCabecera", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("ProcesosService.Domain.Entities.Producto", b =>
                {
                    b.Navigation("ComprasDetalle");
                });
#pragma warning restore 612, 618
        }
    }
}
