// <auto-generated />
using System;
using ClientesService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClientesService.Migrations
{
    [DbContext(typeof(ClienteDbContext))]
    partial class ClientesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClientesService.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCliente"));

                    b.Property<string>("Correo")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("NumeroIdentificacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TipoIdentificacionFiscal")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("TipoPersona")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdCliente");

                    b.HasIndex("TipoIdentificacionFiscal", "NumeroIdentificacion")
                        .IsUnique();

                    b.ToTable("Clientes", (string)null);

                    b.HasData(
                        new
                        {
                            IdCliente = 1,
                            Correo = "consumidor.final@ferreteria.local",
                            Direccion = "N/A",
                            Estado = true,
                            FechaRegistro = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumeroIdentificacion = "9999999999999",
                            Telefono = "N/A",
                            TipoIdentificacionFiscal = "ConsumidorFinal",
                            TipoPersona = "Natural"
                        });
                });

            modelBuilder.Entity("ClientesService.Domain.Entities.ClienteJuridico", b =>
                {
                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("IdCliente");

                    b.ToTable("ClientesJuridicos", (string)null);
                });

            modelBuilder.Entity("ClientesService.Domain.Entities.ClienteNatural", b =>
                {
                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdCliente");

                    b.ToTable("ClientesNaturales", (string)null);

                    b.HasData(
                        new
                        {
                            IdCliente = 1,
                            Apellidos = "Final",
                            Nombres = "Consumidor"
                        });
                });

            modelBuilder.Entity("ClientesService.Domain.Entities.ClienteJuridico", b =>
                {
                    b.HasOne("ClientesService.Domain.Entities.Cliente", "Cliente")
                        .WithOne("ClienteJuridico")
                        .HasForeignKey("ClientesService.Domain.Entities.ClienteJuridico", "IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("ClientesService.Domain.Entities.ClienteNatural", b =>
                {
                    b.HasOne("ClientesService.Domain.Entities.Cliente", "Cliente")
                        .WithOne("ClienteNatural")
                        .HasForeignKey("ClientesService.Domain.Entities.ClienteNatural", "IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("ClientesService.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("ClienteJuridico");

                    b.Navigation("ClienteNatural");
                });
#pragma warning restore 612, 618
        }
    }
}
